#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible/roles/rancher-worker
- name: Reiniciar RKE2 agent
  become: true
  ansible.builtin.systemd:
      name: rke2-agent
      state: restarted
      daemon_reload: true