[defaults]
host_key_checking=False

[control_plane]
node-1  ansible_host=<ip_definida_en_variables_tf>

[control_plane:vars]
ansible_user=<username_elegido>
ansible_ssh_private_key_file=<ruta_a_ssh_privada>
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[workers]
node-2  ansible_host=<ip_definida_en_variables_tf>
node-3  ansible_host=<ip_definida_en_variables_tf>

[workers:vars]
ansible_user=<username_elegido> 
ansible_ssh_private_key_file=<ruta_a_ssh_privada>
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
